[package]
name = "CrypText"
version = "0.1.0"
edition = "2024"
default-run = "CrypText"
[dependencies]
anyhow = "1.0.98"
tokio={version="1", features=["full"]}
aes = "0.8"
aes-gcm = "0.10"
rand = "0.8"
base64 = "0.21"
x25519-dalek = "2"
rand_core = "0.6"
sha2 = "0.10"