// Auto-generated embedded constants - DO NOT EDIT
// This file is generated by build.rs during compilation

pub const EMBEDDED_USERS: &str = "[
  {
    \"username\": \"test\",
    \"password_hash\": \"$argon2id$v=19$m=4096,t=3,p=1$c29tZVNhbHQ$EMUZdlmqcxdNr9QfF5YlPw\",
    \"salt\": \"some Salt\",
    \"created_at\": 1700000000,
    \"is_admin\": false,
    \"vpn_ip\": null
  },
  {
    \"username\": \"lucifer\",
    \"password_hash\": \"$argon2id$v=19$m=19456,t=2,p=1$/Xcc3D8mDj3HkqyNccJvHQ$RtJhoyoD/OMGmU+vai9H3JAF2mB7XChV2fRc9RjMOuE\",
    \"salt\": \"Ds02/4w76kDcDXzXLXE3xA\",
    \"created_at\": 1753628444,
    \"is_admin\": false,
    \"vpn_ip\": null
  }
]";
pub const EMBEDDED_ADMIN_CONFIG: &str = "{
  \"password_hash\": \"30c2b71352398b7f\",
  \"salt\": \"1da7b3697808e727\",
  \"setup_complete\": true,
  \"created_at\": \"2025-08-12T13:48:36Z\",
  \"last_updated\": \"2025-08-12T13:48:36Z\",
  \"security_settings\": {
    \"max_failed_attempts\": 3,
    \"session_timeout_hours\": 24,
    \"require_strong_passwords\": true,
    \"enable_2fa\": false
  }
}";
